name: Continuous Integration

on:
  push:
  pull_request:

jobs:
  tests:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@v1
    with:
      libraries: |
        apt:
          - libhdf5-serial-dev
          - libmpich-dev
      envs: |
        - linux: py37-test-bitlevel
          runs-on: ubuntu-20.04
        - linux: py38-test-bitlevel
          runs-on: ubuntu-20.04
        - linux: py39-test-bitlevel
          runs-on: ubuntu-20.04
        - linux: py310-test-bitlevel
          runs-on: ubuntu-20.04
